name: Test

# PR 이 생성되면 테스트 실행
on:
  workflow_dispatch:
  pull_request:
    branches: ['**']

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 받아오기
        uses: actions/checkout@v6

      - name: Node.js 설정하기
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: 의존성 설치
        run: npm install

      - name: Prisma 준비하기
        run: npx prisma generate

      - name: 타입체크
        run: npx tsc --noEmit

  test:
    needs: typecheck
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: panda-market-test
        ports:
          - 5432:5432

    steps:
      - name: 소스코드 받아오기
        uses: actions/checkout@v6

      - name: Node.js 설정하기
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: 의존성 설치
        run: npm install

      - name: Prisma 준비하기
        run: npx prisma generate

      - name: 테스트 실행하기
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/panda-market-test
          JWT_ACCESS_TOKEN_SECRET: your-secret-key
          JWT_REFRESH_TOKEN_SECRET: your-refresh-secret-key
        run: npm test
